server:
  port: 8081

spring:
  # 配置spring data jpa
  jpa:
    # 指定是否在spring容器启动时创建表, 默认false
    generate-ddl: true
    # 指定是否在控制台显示SQL语句, 默认false
    show-sql: true
    # 指定应用重启后不重新更新表内容
    hibernate:
      ddl-auto: none

  # 配置数据源
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///test?useUnicode=true&amp;characterEncoding=utf8
    username: root
    password: root

  # 指定当前微服务名称
  application:
    name: abcmsc-provider-depart

# 配置日志
logging:
  pattern:
    console: level-%level %msg%n

  level:
    root: info
    org.hibernate: info
    # 在show-sql为true时, 显示SQL中的动态参数值
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    # 在show-sql为true时, 显示查询结果
    org.hibernate.hql.internal.ast.exec.BasicExecutor: trace
    com.abc: debug

eureka:
  client:
    service-url:
      # 指定当前Client所要连接的Eureka Server
      defaultZone: http://localhost:8000/eureka
  instance:
    instance-id: abcmsc-provider-8081



# 以下配置需要添加actuator依赖, 可以自由添加描述本应用的一些信息
info:
  version: 1.0
  app.auth: jackyellow
  app.name: abcmsc
  company.name: www.kaikeba.com
  company.addr: 深圳华强北


# 以下是Eureka Client复杂的配置方式
# region与zone的关系是 1:n
# zone与Eureka的关系时 1:n

#eureka:
#  client:
#    # 指定区域名称
#    region: xxx
#    # 指定区域中所包含的地带zone
#    availability-zones:
#      xxx: kkb1, kkb2
#
#    # 指定各个地带zone中所包含的Eureka Server地址
#    service-url:
#      kkb1: http://localhost:8000/eureka
#      kkb2: http://localhost:8000/eureka
#    # 指定要连接的注册中心所在区域
#    fetch-remote-regions-registry: xxx